# -*- coding: utf-8 -*-
"""jd

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W32nM877A-dnbL4IjngPFQCc_cAhng0n
"""

# Install TextBlob if not already installed
!pip install -q textblob
!python -m textblob.download_corpora

from textblob import TextBlob

# Ask the user for input
review = input("Enter your product review: ")

# Create a TextBlob object
blob = TextBlob(review)

# Analyze sentiment
polarity = blob.sentiment.polarity

# Determine sentiment
if polarity > 0:
    sentiment = "Positive"
elif polarity < 0:
    sentiment = "Negative"
else:
    sentiment = "Neutral"

# Print the result
print(f"\nReview: {review}")
print(f"Sentiment: {sentiment} (Polarity Score: {polarity:.2f})")